Upd opt/initramfs scripts (re-write changes= code)

diff --git a/bookworm/rootcopy/opt/initramfs/linuxrc b/bookworm/rootcopy/opt/initramfs/linuxrc
--- a/bookworm/rootcopy/opt/initramfs/linuxrc
+++ b/bookworm/rootcopy/opt/initramfs/linuxrc
@@ -133,7 +133,7 @@ fi
 
 # DATADEV value example /mnt/sda1
 # DATADIR value example /mnt/sda1/live
-[ -d $DATADEV/$FOLDER ] && DATADIR=$DATADEV/$FOLDER || . fatal
+[ -d $DATADEV/$FOLDER ] && DATADIR=$DATADEV/$FOLDER || fatal
 
 echo "${i}using data from $DATADIR"
 # Create file /mnt/live/etc/homedrv for use in
@@ -141,272 +141,31 @@ echo "${i}using data from $DATADIR"
 echo $DATADIR > /etc/homedrv
 
 debug
-pos_fail () {
-		rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-		echo && echo -e "[1;33m""A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem\nhas been detected on $CHANGES or $(echo $CHANGES |sed 's|\(.*\)/.*|\1|') .\nYour changes cannot be saved directly to the specified storage media with this\nsetup.""[0m"
-		echo "press enter to continue in '[1;36mAlways Fresh[0m' mode for this session"
-		read; rmdir /mnt/$DEV/$LPTH/changes 2>/dev/null; fail_chn
-}
-
-pos_fail1 () {
-		rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-echo && echo -e "[1;33m""A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem\nhas been detected on $(echo $CHANGES |sed 's|\(.*\)/.*|\1|').\nYour changes cannot be saved directly to the specified storage media with this\nsetup.""[0m"
-		echo "press enter to continue in '[1;36mAlways Fresh[0m' mode for this session"
-		read; rmdir /mnt/$DEV/$LPTH/changes 2>/dev/null; fail_chn
-
-}
 
 # Setup changes:
+[ $PFULL ] && CHANGES=$PFULL
 
-if [ $PFULL ]; then
-CHANGES=$PFULL
-    echo "${i}setting up directory for changes"
-    CHNEXIT=`echo $CHANGES | cut -d: -f1`; 
-    [ $CHNEXIT = EXIT ] && CHANGES=`echo $CHANGES | cut -d: -f2-`
-    [ $CHNEXIT = +EXIT ] && CHANGES=`echo $CHANGES | cut -d: -f2-`   
-    
-    [ -r $DATADEV/$CHANGES ] && { DEV=`echo $DATADEV | sed s@/mnt/@@`; LPTH=$CHANGES; } || locate -r $CHANGES
-    if [ $? -eq 0 ]; then
-	if [ -d /mnt/$DEV/$LPTH/pfull/filesystem/var ] && [ -d /mnt/$DEV/$LPTH/pfull/filesystem/usr ] && [ -d /mnt/$DEV/$LPTH/pfull/filesystem/root ]; then
-#	    mkdir -p /mnt/$DEV/$LPTH/changes 2>/dev/null && \
-	    mount -o bind /mnt/$DEV/$LPTH/pfull /memory/changes && touch /memory/changes/._test1 2>/dev/null
+if [ $CHANGES ]; then
+	echo "${i}setting up directory for changes"
+	CHNEXIT=`echo $CHANGES | cut -d: -f1`
+	[ $CHNEXIT = EXIT ] && CHANGES=`echo $CHANGES | cut -d: -f2-`
+	[ $CHNEXIT = +EXIT ] && CHANGES=`echo $CHANGES | cut -d: -f2-`
+	[ -r $DATADEV/$CHANGES ] && { DEV=`echo $DATADEV | sed s@/mnt/@@`; LPTH=$CHANGES; } || locate -r $CHANGES
+	if [ $? -eq 0 ]; then setup_changes_dir_or_dat #finit setup_changes_dir_or_dat()
+		if [ $? -eq 0 ]; then setup_changes #finit setup_changes()
+		else
+			echo "${i}changes not writable, using memory instead"
+			umount /memory/changes 2>/dev/null
+			fail_chn
+		fi
 	else
-echo && echo
-echo "${CYAN}Data not found for pseudo-full install /mnt/$DEV/$LPTH/pfull
-Press space/enter to unmount all devices and reboot or any other key
-to drop to the debug shell.${RST}"
-read -s -n1 ans
-if [ "$ans" = "" ]; then
-    umount /mnt/* 2>/dev/null
-    umount -a 2>/dev/null
-    reboot -f
+		#Can not locate changes dir
+		fail $CHANGES
+		fail_chn
+	fi
 else
-echo "${CYAN}Here is debugging shell for you, unmount all partitions
-and press Ctrl+Alt+Del when you finish. Good luck!${RST}"
-sh
-fi
-	fi
-	if [ $? -eq 0 ]; then
-	    echo "${i}testing filesystem on $CHANGES for posix compatibility"
-	    ln -s /memory/changes/._test1 /memory/changes/._test2 2>/dev/null && chmod +x /memory/changes/._test1 2>/dev/null && [ -x /memory/changes/._test1 ] && chmod -x /memory/changes/._test1 2>/dev/null && [ ! -x /memory/changes/._test1 ] && rm -f /memory/changes/._test1 /memory/changes/._test2
-ret=$? 
-	    if [ $ret -ne 0 ]; then
-            posfail=yes
-            fi
-if [ $CHNEXIT = +EXIT ];then
-  if [ ! -d /mnt/$DEV/$LPTH ]; then
-  APTH=$(echo /mnt/$DEV/$LPTH |sed 's|\(.*\)/.*|\1|')
-    rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-#	    mkdir -p $APTH/changes 2>/dev/null && \
-	    mount -o bind $APTH/pfull /memory/changes && touch /memory/changes/._test1 2>/dev/null
-  else
-    rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-#	    mkdir -p /mnt/$DEV/$LPTH/changes 2>/dev/null && \
-	    mount -o bind /mnt/$DEV/$LPTH/pfull /memory/changes && touch /memory/changes/._test1 2>/dev/null
-  fi
-	    ln -s /memory/changes/._test1 /memory/changes/._test2 2>/dev/null && chmod +x /memory/changes/._test1 2>/dev/null && [ -x /memory/changes/._test1 ] && chmod -x /memory/changes/._test1 2>/dev/null && [ ! -x /memory/changes/._test1 ] && rm -f /memory/changes/._test1 /memory/changes/._test2
-fi
-ret1=$?
-
-            if [ $ret -ne 0 ] && [ "$posfail" = "yes" ]; then
-		rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-		echo && echo -e "[1;33m""A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem\nhas been detected on $CHANGES or $(echo $CHANGES |sed 's|\(.*\)/.*|\1|') .\nYour changes cannot be saved directly to the specified storage media with this\nsetup. Please use the '[1;36m Save file manager[1;33m' to create a .dat container\nand use it for saving your changes after your next reboot.""[0m"
-		echo "boot will continue in '[1;36mAlways Fresh[0m' mode for this session"
-		sleep 10; rmdir /mnt/$DEV/$LPTH/changes; fail_chn
-
-            elif [ $ret1 -ne 0 ] && [ -z "$posfail" ]; then
-		rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-echo && echo -e "[1;33m""A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem\nhas been detected on $(echo $CHANGES |sed 's|\(.*\)/.*|\1|').\nYour changes cannot be saved directly to the specified storage media with this\nsetup.""[0m"
-		echo "press enter to continue in '[1;36mAlways Fresh[0m' mode for this session"
-		read; rmdir /mnt/$DEV/$LPTH/changes 2>/dev/null; fail_chn
-
-	    else
-		echo "${i}filesystem is posix compatible"; CHNDEV=/mnt/$DEV
-
-        	if [ -f /memory/changes/clear-changes-on-reboot ]; then
-                      echo "${i}${CYAN}changes content signalled to be cleared${RST}"
-                      rm -rf /memory/changes/*
-		fi
-	    	    	    
-		if [ "$CHNEXIT" = EXIT -o "`egrep -o " changes-ro( |\$)" /proc/cmdline`" ]; then
-		    CHNEXIT=$CHNDEV/$LPTH; echo $CHNEXIT >/tmp/changes-exit
-		    param changes-ro && echo "${i}${CYAN}changes will not be saved for this session${RST}" || echo "${i}${CYAN}changes will be saved only during reboot/shutdown${RST}"
-
-			setClean
-			mkdir -p /memory/images/changes-exit
-			mount -o move /memory/changes /memory/images/changes-exit
-			umount /memory/changes 2>/dev/null;
-			mount -t tmpfs -o size=$RAMSIZE tmpfs /memory/changes;
-			CHANGES=memory
-		fi
-
-		 if [ $CHNEXIT = +EXIT ]; then
-		    CHNEXIT=$CHNDEV/$LPTH; echo $CHNEXIT >/tmp/changes-exit
-		    echo "${i}${CYAN}changes will be saved only during reboot/shutdown${RST}"
-
-  	      if [ ! -d /mnt/$DEV/$LPTH ]; then
-              APTH=$(echo /mnt/$DEV/$LPTH |sed 's|\(.*\)/.*|\1|')
-  	      echo "${i}${CYAN}option +EXIT is being used, changes are NOT written in memory${RST}"
-  	      echo "${i}${CYAN}temporary changes will be in $APTH/tmp-pfull ${RST}"
-umount /memory/changes 2>/dev/null; rmdir $APTH/changes 2>/dev/null
-mount -o loop /mnt/$DEV/$LPTH /memory/changes 2>/dev/null
-			setClean
-
-			mkdir -p /memory/images/changes-exit
-			mount -o move /memory/changes /memory/images/changes-exit
-			#umount /memory/changes 2>/dev/null;
-			#mount -nt tmpfs -o size=$RAMSIZE tmpfs /memory/changes;
-			#CHANGES=memory
-  	      rm -rf $APTH/tmp-pfull 2> /dev/null
-  	      mkdir -p $APTH/tmp-pfull
-  	      mount -o bind $APTH/tmp-pfull /memory/changes
-  	      else
-  	      echo "${i}${CYAN}option +EXIT is being used, changes are NOT written in memory${RST}"
-  	      echo "${i}${CYAN}temporary changes will be in /mnt/$DEV/$LPTH/tmp-pfull${RST}"
-		    #umount /memory/changes;
-			setClean
-			mkdir -p /memory/images/changes-exit
-			mount -o move /memory/changes /memory/images/changes-exit
-			umount /memory/changes 2>/dev/null;
-			#mount -nt tmpfs -o size=$RAMSIZE tmpfs /memory/changes;
-			#CHANGES=memory
-  	      rm -rf /mnt/$DEV/$LPTH/tmp-pfull 2> /dev/null
-  	      mkdir -p /mnt/$DEV/$LPTH/tmp-pfull
-  	      mount -o bind /mnt/$DEV/$LPTH/tmp-pfull /memory/changes
-
-
-  	      fi
-		fi
-	    fi
-	else
-	    echo "${i}changes not writable, using memory instead"; CHGERR=2; umount /memory/changes 2>/dev/null; fail_chn
-	fi
-    else
-	fail $CHANGES; fail_chn
-    fi
-
-elif [ $CHANGES ]; then
-    echo "${i}setting up directory for changes"
-    CHNEXIT=`echo $CHANGES | cut -d: -f1`; 
-    [ $CHNEXIT = EXIT ] && CHANGES=`echo $CHANGES | cut -d: -f2-`
-    [ $CHNEXIT = +EXIT ] && CHANGES=`echo $CHANGES | cut -d: -f2-`   
-    
-    [ -r $DATADEV/$CHANGES ] && { DEV=`echo $DATADEV | sed s@/mnt/@@`; LPTH=$CHANGES; } || locate -r $CHANGES
-    if [ $? -eq 0 ]; then
-	if [ -d /mnt/$DEV/$LPTH ]; then
-	    mkdir -p /mnt/$DEV/$LPTH/changes 2>/dev/null && \
-	    mount -o bind /mnt/$DEV/$LPTH/changes /memory/changes && touch /memory/changes/._test1 2>/dev/null
-	else
-	    if blkid /mnt/$DEV/$LPTH 2>/dev/null | cut -d" " -f3- | grep -q _LUKS; then
-		for x in dm_crypt cryptd cbc sha256_generic aes_generic aes_x86_64; do modprobe $x 2>/dev/null; done
-		losetup /dev/loop2 /mnt/$DEV/$LPTH
-		echo "${i}found encrypted .dat container"
-		cryptsetup luksOpen /dev/loop2 crypt
-		mount /dev/mapper/crypt /memory/changes 2>/dev/null && touch /memory/changes/._test1 2>/dev/null
-	    else
-		mount -o loop /mnt/$DEV/$LPTH /memory/changes 2>/dev/null && touch /memory/changes/._test1 2>/dev/null
-	    fi
-	fi
-	if [ $? -eq 0 ]; then
-	    echo "${i}testing filesystem on $CHANGES for posix compatibility"
-	    ln -s /memory/changes/._test1 /memory/changes/._test2 2>/dev/null && chmod +x /memory/changes/._test1 2>/dev/null && [ -x /memory/changes/._test1 ] && chmod -x /memory/changes/._test1 2>/dev/null && [ ! -x /memory/changes/._test1 ] && rm -f /memory/changes/._test1 /memory/changes/._test2
-ret=$? 
-	    if [ $ret -ne 0 ]; then
-            posfail=yes
-            fi
-if [ $CHNEXIT = +EXIT ];then
-  if [ ! -d /mnt/$DEV/$LPTH ]; then
-  APTH=$(echo /mnt/$DEV/$LPTH |sed 's|\(.*\)/.*|\1|')
-    rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-	    mkdir -p $APTH/changes 2>/dev/null && \
-	    mount -o bind $APTH/changes /memory/changes && touch /memory/changes/._test1 2>/dev/null
-  else
-    rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-	    mkdir -p /mnt/$DEV/$LPTH/changes 2>/dev/null && \
-	    mount -o bind /mnt/$DEV/$LPTH/changes /memory/changes && touch /memory/changes/._test1 2>/dev/null
-  fi
-	    ln -s /memory/changes/._test1 /memory/changes/._test2 2>/dev/null && chmod +x /memory/changes/._test1 2>/dev/null && [ -x /memory/changes/._test1 ] && chmod -x /memory/changes/._test1 2>/dev/null && [ ! -x /memory/changes/._test1 ] && rm -f /memory/changes/._test1 /memory/changes/._test2
-fi
-ret1=$?
-
-            if [ $ret -ne 0 ] && [ "$posfail" = "yes" ]; then
-		rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-		echo && echo -e "[1;33m""A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem\nhas been detected on $CHANGES or $(echo $CHANGES |sed 's|\(.*\)/.*|\1|') .\nYour changes cannot be saved directly to the specified storage media with this\nsetup. Please use the '[1;36m Save file manager[1;33m' to create a .dat container\nand use it for saving your changes after your next reboot.""[0m"
-		echo "boot will continue in '[1;36mAlways Fresh[0m' mode for this session"
-		sleep 10; rmdir /mnt/$DEV/$LPTH/changes; fail_chn
-
-            elif [ $ret1 -ne 0 ] && [ -z "$posfail" ]; then
-		rm -f /memory/changes/._test1 /memory/changes/._test2; umount /memory/changes
-echo && echo -e "[1;33m""A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem\nhas been detected on $(echo $CHANGES |sed 's|\(.*\)/.*|\1|').\nYour changes cannot be saved directly to the specified storage media with this\nsetup.""[0m"
-		echo "press enter to continue in '[1;36mAlways Fresh[0m' mode for this session"
-		read; rmdir /mnt/$DEV/$LPTH/changes 2>/dev/null; fail_chn
-
-	    else
-		echo "${i}filesystem is posix compatible"; CHNDEV=/mnt/$DEV
-
-        	if [ -f /memory/changes/clear-changes-on-reboot ]; then
-                      echo "${i}${CYAN}changes content signalled to be cleared${RST}"
-                      rm -rf /memory/changes/*
-		fi
-	    	    	    
-		if [ "$CHNEXIT" = EXIT -o "`egrep -o " changes-ro( |\$)" /proc/cmdline`" ]; then
-		    CHNEXIT=$CHNDEV/$LPTH; echo $CHNEXIT >/tmp/changes-exit
-		    param changes-ro && echo "${i}${CYAN}changes will not be saved for this session${RST}" || echo "${i}${CYAN}changes will be saved only during reboot/shutdown${RST}"
-
-			setClean
-			mkdir -p /memory/images/changes-exit
-			mount -o move /memory/changes /memory/images/changes-exit
-			umount /memory/changes 2>/dev/null;
-			mount -t tmpfs -o size=$RAMSIZE tmpfs /memory/changes;
-			CHANGES=memory
-		fi
-
-		 if [ $CHNEXIT = +EXIT ]; then
-		    CHNEXIT=$CHNDEV/$LPTH; echo $CHNEXIT >/tmp/changes-exit
-		    echo "${i}${CYAN}changes will be saved only during reboot/shutdown${RST}"
-
-  	      if [ ! -d /mnt/$DEV/$LPTH ]; then
-              APTH=$(echo /mnt/$DEV/$LPTH |sed 's|\(.*\)/.*|\1|')
-  	      echo "${i}${CYAN}option +EXIT is being used, changes are NOT written in memory${RST}"
-  	      echo "${i}${CYAN}temporary changes will be in $APTH/tmp-changes ${RST}"
-umount /memory/changes 2>/dev/null; rmdir $APTH/changes 2>/dev/null
-mount -o loop /mnt/$DEV/$LPTH /memory/changes 2>/dev/null
-			setClean
-
-			mkdir -p /memory/images/changes-exit
-			mount -o move /memory/changes /memory/images/changes-exit
-			#umount /memory/changes 2>/dev/null;
-			#mount -nt tmpfs -o size=$RAMSIZE tmpfs /memory/changes;
-			#CHANGES=memory
-  	      rm -rf $APTH/tmp-changes 2> /dev/null
-  	      mkdir -p $APTH/tmp-changes
-  	      mount -o bind $APTH/tmp-changes /memory/changes
-  	      else
-  	      echo "${i}${CYAN}option +EXIT is being used, changes are NOT written in memory${RST}"
-  	      echo "${i}${CYAN}temporary changes will be in /mnt/$DEV/$LPTH/tmp-changes ${RST}"
-		    #umount /memory/changes;
-			setClean
-			mkdir -p /memory/images/changes-exit
-			mount -o move /memory/changes /memory/images/changes-exit
-			umount /memory/changes 2>/dev/null;
-			#mount -nt tmpfs -o size=$RAMSIZE tmpfs /memory/changes;
-			#CHANGES=memory
-  	      rm -rf /mnt/$DEV/$LPTH/tmp-changes 2> /dev/null
-  	      mkdir -p /mnt/$DEV/$LPTH/tmp-changes
-  	      mount -o bind /mnt/$DEV/$LPTH/tmp-changes /memory/changes
-
-
-  	      fi
-		fi
-	    fi
-	else
-	    echo "${i}changes not writable, using memory instead"; CHGERR=2; umount /memory/changes 2>/dev/null; fail_chn
-	fi
-    else
-	fail $CHANGES; fail_chn
-    fi
-else
-     echo "${i}changes cheatcode not found, using memory only"; fail_chn
+	echo "${i}changes cheatcode not found, using memory only"
+	fail_chn
 fi
 
 if [ $PFULL ]; then
@@ -482,21 +241,6 @@ fi
 #--------------------------------------
 IncludeModules
 
-# Add "changes on exit" device/file/folder:
-#if [ -e /tmp/changes-exit ]; then
-#    mkdir /memory/images/changes
-#    if [ -d $CHNEXIT ]; then
-#	mount -o bind $CHNEXIT/changes /memory/images/changes
-#    elif [ -b /dev/mapper/crypt ]; then
-#	mount /dev/mapper/crypt /memory/images/changes
-#    else
-#	mount -o loop $CHNEXIT /memory/images/changes
-#    fi
-#    echo "  $m  changes"; mount -no remount,add:1:/memory/images/changes=ro aufs /union
-#    echo $CHNEXIT/changes >>/tmp/modules
-#    param changes-ro && rm /tmp/changes-exit
-#fi
-
 debug
 
 # Copy /rootcopy folder:
@@ -569,18 +313,27 @@ fi
 MNTPOINTS=`grep /mnt/ /etc/fstab | cut -d" " -f2`
 [ -d /mnt/nfs ] && MNTPOINTS="/mnt/nfs $MNTPOINTS"
 [ -d /mnt/isoloop ] && MNTPOINTS="/mnt/isoloop $MNTPOINTS"
+if [ $CHNDEV ] && [ -d $CHNDEV ]; then
+MNTPOINTS="$CHNDEV $MNTPOINTS"
+fi
 
 # Move mountpoints /mnt/XX to /union/mnt/XX
 for MNTDEV in $MNTPOINTS
 do mkdir -p /union"$MNTDEV"
 if [ "$MNTDEV" = "$CHNDEV" ]; then
 	if [ "$CHNEXIT" ] && param copy2ram ; then
-	umount "$MNTDEV" 2>/dev/null || mount -o move "$MNTDEV" /union"$MNTDEV"
-	continue
-	else continue # keep CHNDEV mounted
+		mount -o move "$MNTDEV" /union"$MNTDEV" # && umount /union"$MNTDEV" 2>/dev/null
+		continue
+	else
+		mount -o move "$MNTDEV" /union"$MNTDEV"
+		continue # keep CHNDEV mounted
 	fi
 elif [ "$MNTDEV" = "$DATADEV" -o "$MNTDEV" = "$BOOTDEV" ]; then
-	param copy2ram && umount "$MNTDEV" 2>/dev/null || mount -o move "$MNTDEV" /union"$MNTDEV"
+	if param noauto && param copy2ram ; then
+		umount "$MNTDEV" 2>/dev/null || mount -o move "$MNTDEV" /union"$MNTDEV"
+	else
+		mount -o move "$MNTDEV" /union"$MNTDEV"
+	fi
 	continue
 fi
 param noauto && umount "$MNTDEV" 2>/dev/null || mount -o move "$MNTDEV" /union"$MNTDEV"
@@ -613,6 +366,7 @@ echo $DATADEV > /etc/cfgdev # used in script 'pseudofull-setup'
 echo -e "\n# Booting device:\n$DATADEV
 \n# data found in:\n$DATADIR
 \n# Changes are stored in:\n$CHANGES
+# CHNDEV=$CHNDEV
 \n# Non standard /rootcopy dir:\n$ROOTCOPY
 \n# Modules activated during boot time:" >>$livedbg
 cat /tmp/modules >>$livedbg
